on: release
name: Publish Release
jobs:
  wordPressPackageDeploy:
    name: WordPress Package Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm build
      - name: WordPress Plugin Deploy
        uses: Arvernus/action-arvernus-release-update@master
        with:
          package-type: "Plugin"
          server-secret-key: ${{ secrets.SERVER_SECRET_KEY }}
          github-access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
